"use client";

import { useEffect, useState } from "react";

type AdminReviewRow = { id: string; requestType: string; itemCode?: string | null; status: string; remarks?: string | null; details?: Record<string, unknown> | null; user?: { name: string; email: string } | null; project?: { referenceNumber: string } | null };

export default function AdminReviewsClient() {
  const [rows, setRows] = useState<AdminReviewRow[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [busyId, setBusyId] = useState<string | null>(null);
  async function load() { const response = await fetch("/api/admin/reviews"); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Failed to load admin reviews"); setRows(body.requests || []); }
  useEffect(() => { load().catch((err) => setError(err.message)); }, []);
  async function process(row: AdminReviewRow, decision: "APPROVED" | "REJECTED") { const remarks = window.prompt(`${decision} remarks`, row.remarks || "") || ""; setBusyId(row.id); setError(null); setMessage(null); try { const response = await fetch(`/api/admin/reviews/${row.id}/process`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision, remarks }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Process failed"); setMessage(`Review ${decision.toLowerCase()}`); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Process failed"); } finally { setBusyId(null); } }
  return <section className="space-y-6"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-700">Admin reviews</p><h1 className="mt-2 text-2xl font-bold text-slate-950">Pending Review Requests</h1><p className="mt-2 text-sm text-slate-500">Approve/reject user correction requests and apply supported catalog changes.</p></div>{error && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{message && <p className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</p>}<div className="rounded-3xl border border-slate-200 bg-white shadow-sm overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-6 py-3">User</th><th className="px-6 py-3">Type</th><th className="px-6 py-3">Item</th><th className="px-6 py-3">Details</th><th className="px-6 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={row.id}><td className="px-6 py-4">{row.user?.name || row.user?.email || "—"}</td><td className="px-6 py-4 font-semibold">{row.requestType}</td><td className="px-6 py-4">{row.itemCode || "—"}</td><td className="px-6 py-4"><pre className="max-w-md whitespace-pre-wrap rounded-xl bg-slate-50 p-3 text-xs text-slate-600">{JSON.stringify(row.details || {}, null, 2)}</pre></td><td className="px-6 py-4 text-right"><div className="flex justify-end gap-2"><button disabled={busyId === row.id} onClick={() => process(row, "APPROVED")} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Approve</button><button disabled={busyId === row.id} onClick={() => process(row, "REJECTED")} className="rounded-lg bg-red-600 px-3 py-2 text-xs font-bold text-white">Reject</button></div></td></tr>)}{!rows.length && <tr><td colSpan={5} className="px-6 py-10 text-center text-slate-500">No pending admin review requests.</td></tr>}</tbody></table></div></section>;
}
