@echo off
setlocal EnableExtensions

echo.
echo ============================================================
echo  GE-FOS-NEXT Document Parity Proof Runner v2
echo ============================================================

set "PROJECT_ROOT=%CD%"
set "OLD_ROOT=D:\OneDrive - Green Energy\Sakib\GE\Financial-Offer-Challan-Purchase-Order-System Stable"
set "STORAGE_ROOT=%PROJECT_ROOT%\storage"
set "PROOF_DIR=%PROJECT_ROOT%\document-parity-proof"
set "OLD_EXPORTS=%OLD_ROOT%\data_storage\FOS"
set "NEW_EXPORTS=%STORAGE_ROOT%\exports"
set "REPORT_JSON=%PROJECT_ROOT%\docs\migration\golden-document-comparison.json"
set "ASSET_MANIFEST=%PROJECT_ROOT%\docs\migration\document-assets-manifest.json"

echo Project root: %PROJECT_ROOT%
echo Old root:     %OLD_ROOT%
echo Storage root: %STORAGE_ROOT%
echo.

if not exist "%OLD_ROOT%" (
  echo ERROR: Old stable folder not found:
  echo %OLD_ROOT%
  goto failed
)

if not exist "%PROJECT_ROOT%\package.json" (
  echo ERROR: package.json not found. Run this from the GE-FOS-NEXT project root.
  goto failed
)

mkdir "%STORAGE_ROOT%" 2>nul
mkdir "%PROJECT_ROOT%\docs\migration" 2>nul
mkdir "%PROOF_DIR%" 2>nul
mkdir "%PROOF_DIR%\old-samples" 2>nul
mkdir "%PROOF_DIR%\new-exports" 2>nul

echo [1/8] Appending document asset env values to .env.local ...
(
  echo.
  echo # Document parity asset settings - generated by RUN_DOCUMENT_PARITY_PROOF.cmd
  echo FOS_STORAGE_ROOT=%STORAGE_ROOT%
  echo FOS_PDF_ASSET_MODE=letterhead-only
  echo FOS_LETTERHEAD_STORAGE_KEY=assets/letterhead.pdf
  echo FOS_LOGO_STORAGE_KEY=
  echo FOS_OFFER_LOGO_STORAGE_KEY=assets/amoge_logo.png
  echo FOS_CHALLAN_LOGO_STORAGE_KEY=assets/amoge_logo.png
  echo FOS_PURCHASE_ORDER_LOGO_STORAGE_KEY=assets/NAFFCO_Logo_New.png
  echo FOS_SIGNATURE_STORAGE_KEY=assets/signatures/Signature_RIF.png
  echo FOS_PO_INCLUDE_SIGNATURE=false
  echo FOS_PO_SIGNATURE_STORAGE_KEY=
  echo FOS_PDF_TITLE_Y=800
  echo FOS_PDF_SUBTITLE_Y=783
  echo FOS_PDF_SEPARATOR_Y=775
  echo FOS_PDF_CONTENT_TOP_Y=760
  echo FOS_PDF_BOTTOM_Y=125
  echo FOS_SIGNATURE_SAFE_PADDING=18
) >> "%PROJECT_ROOT%\.env.local"
if errorlevel 1 goto failed

echo [2/8] Running Prisma migration deploy ...
call pnpm prisma migrate deploy
if errorlevel 1 goto failed

echo [3/8] Running build ...
call pnpm build
if errorlevel 1 goto failed

echo [4/8] Copying/migrating document assets from old app ...
call pnpm migration:document-assets "%OLD_ROOT%"
if errorlevel 1 goto failed

echo [5/8] Copying old generated sample files into proof folder ...
if exist "%OLD_EXPORTS%" (
  xcopy "%OLD_EXPORTS%\*.pdf" "%PROOF_DIR%\old-samples\" /Y /I >nul 2>nul
  xcopy "%OLD_EXPORTS%\*.xlsx" "%PROOF_DIR%\old-samples\" /Y /I >nul 2>nul
) else (
  echo WARNING: Old exports folder not found: %OLD_EXPORTS%
)

echo [6/8] Running golden comparison if new exports exist ...
if exist "%NEW_EXPORTS%" (
  call pnpm documents:compare-golden "%OLD_EXPORTS%" "%NEW_EXPORTS%" "%REPORT_JSON%"
  if errorlevel 1 echo WARNING: comparison command returned an error. Continue packaging proof folder.
  xcopy "%NEW_EXPORTS%\*.pdf" "%PROOF_DIR%\new-exports\" /Y /I >nul 2>nul
  xcopy "%NEW_EXPORTS%\*.xlsx" "%PROOF_DIR%\new-exports\" /Y /I >nul 2>nul
) else (
  echo WARNING: New exports folder does not exist yet.
  echo Export PDF/XLSX from the app, then run this CMD again.
)

echo [7/8] Copying comparison reports into proof folder ...
if exist "%REPORT_JSON%" copy /Y "%REPORT_JSON%" "%PROOF_DIR%\golden-document-comparison.json" >nul
if exist "%ASSET_MANIFEST%" copy /Y "%ASSET_MANIFEST%" "%PROOF_DIR%\document-assets-manifest.json" >nul

(
  echo GE-FOS-NEXT Document Parity Proof Notes
  echo =======================================
  echo.
  echo Project root: %PROJECT_ROOT%
  echo Old root: %OLD_ROOT%
  echo Storage root: %STORAGE_ROOT%
  echo Old exports: %OLD_EXPORTS%
  echo New exports: %NEW_EXPORTS%
  echo.
  echo What to do after first successful run:
  echo 1. Run: pnpm dev
  echo 2. Export real Offer PDF/XLSX, Challan PDF/XLSX, Purchase Order PDF/XLSX from the app.
  echo 3. Stop dev server with Ctrl+C.
  echo 4. Run RUN_DOCUMENT_PARITY_PROOF.cmd again.
  echo 5. Send document-parity-proof.zip.
  echo.
  echo Manual checks required:
  echo - normal user export hides PO columns
  echo - admin export shows PO columns only when po_price is visible
  echo - T^&C and summary match old output
  echo - letterhead/logo/signature/cover do not overlap content
  echo - page breaks are clean
) > "%PROOF_DIR%\README_PROOF_NOTES.txt"

echo [8/8] Creating document-parity-proof.zip ...
powershell -NoProfile -ExecutionPolicy Bypass -Command "if(Test-Path 'document-parity-proof.zip'){Remove-Item 'document-parity-proof.zip' -Force}; Compress-Archive -Path 'document-parity-proof' -DestinationPath 'document-parity-proof.zip' -Force"
if errorlevel 1 goto failed

echo.
echo ============================================================
echo DONE.
echo Created: %PROJECT_ROOT%\document-parity-proof.zip
echo ============================================================
echo.
echo If you have not exported new files from the app yet, run:
echo pnpm dev
echo Then export PDF/XLSX files, stop server with Ctrl+C, and run this CMD again.
echo.
pause
exit /b 0

:failed
echo.
echo ============================================================
echo FAILED. Read the error above.
echo ============================================================
pause
exit /b 1
