import { randomUUID } from "node:crypto";
import type { SessionUser } from "@/lib/auth/session";
import { prisma } from "@/lib/db/prisma";
import { canAccessProject } from "@/lib/permissions/rbac";
import { richTextToPlainText, sanitizeLegacyRichText } from "@/lib/validators/sanitize-html";
import type { PurchaseOrderSaveInput } from "@/lib/validators/purchase-order-project";

function text(value: unknown) { const out = value === null || value === undefined ? "" : String(value).trim(); return out || null; }
function decimal(value: unknown) { if (value === null || value === undefined || value === "") return null; const n = Number(String(value).replace(/,/g, "")); return Number.isFinite(n) ? String(value) : null; }
function total(qty: unknown, price: unknown) { const q = Number(String(qty ?? 0).replace(/,/g, "")); const p = Number(String(price ?? 0).replace(/,/g, "")); return (Number.isFinite(q) && Number.isFinite(p) ? q * p : 0).toFixed(2); }
function normalizeItem(item: PurchaseOrderSaveInput["items"][number], projectId: string, sortOrder: number) { const html = sanitizeLegacyRichText(item.descriptionHtml || item.descriptionPlain || ""); return { id: randomUUID(), projectId, sortOrder, sourceType: item.sourceType, catalogItemId: item.catalogItemId || null, itemCode: text(item.itemCode), productType: text(item.productType), make: text(item.make), model: text(item.model), approvals: text(item.approvals), descriptionHtml: html, descriptionPlain: richTextToPlainText(html), qty: decimal(item.qty), unit: text(item.unit), poPriceUsd: decimal(item.poPriceUsd), poTotalUsd: total(item.qty, item.poPriceUsd), poPriceBdt: decimal(item.poPriceBdt), isCustom: item.sourceType === "CUSTOM" || !item.catalogItemId, metadata: (item.metadata ?? item) as never }; }
export async function getPurchaseOrderForAdmin(projectId: string, user: SessionUser) { if (user.role !== "ADMIN") return null; const project = await prisma.project.findUnique({ where: { id: projectId }, include: { items: { orderBy: { sortOrder: "asc" } }, owner: { select: { id: true, name: true, email: true, signatureStorageKey: true } }, shares: { select: { sharedWithUserId: true, permission: true } }, parentProject: { select: { id: true, referenceNumber: true } } } }); if (!project || project.deletedAt || project.projectType !== "PURCHASE_ORDER") return null; return project; }
export function serializePurchaseOrder(project: NonNullable<Awaited<ReturnType<typeof getPurchaseOrderForAdmin>>>) { return { id: project.id, referenceNumber: project.referenceNumber, status: project.status, clientSnapshot: project.clientSnapshot, metadata: project.metadata, parentProject: project.parentProject, items: project.items.map((item: any) => ({ id: item.id, sourceType: item.sourceType, catalogItemId: item.catalogItemId, itemCode: item.itemCode, productType: item.productType, make: item.make, model: item.model, approvals: item.approvals, descriptionPlain: item.descriptionPlain, descriptionHtml: item.descriptionHtml, qty: item.qty?.toString() || "", unit: item.unit, poPriceUsd: item.poPriceUsd?.toString() || "", poPriceBdt: item.poPriceBdt?.toString() || "" })) }; }
export async function savePurchaseOrder({ user, projectId, input }: { user: SessionUser; projectId?: string; input: PurchaseOrderSaveInput }) { if (user.role !== "ADMIN") throw new Error("Admin access required"); const existing = projectId ? await prisma.project.findUnique({ where: { id: projectId } }) : null; if (projectId && !existing) throw new Error("Purchase order not found"); if (existing && (existing.projectType !== "PURCHASE_ORDER" || existing.deletedAt)) throw new Error("Purchase order edit denied"); const id = existing?.id || randomUUID(); const metadata = { ...(input.metadata || {}), purchaseOrder: { terms: input.terms || "", originalOfferReference: input.originalOfferReference || "" } }; return prisma.$transaction(async (tx: any) => { const project = existing ? await tx.project.update({ where: { id }, data: { referenceNumber: input.referenceNumber, status: input.status, clientSnapshot: (input.clientSnapshot ?? undefined) as never, parentProjectId: input.originalOfferProjectId || existing.parentProjectId, metadata: metadata as never, lastModifiedAt: new Date() } }) : await tx.project.create({ data: { id, referenceNumber: input.referenceNumber, projectType: "PURCHASE_ORDER", status: input.status, ownerUserId: user.id, parentProjectId: input.originalOfferProjectId || null, clientSnapshot: (input.clientSnapshot ?? undefined) as never, metadata: metadata as never, lastModifiedAt: new Date() } }); await tx.projectItem.deleteMany({ where: { projectId: id } }); for (const [index, item] of input.items.entries()) await tx.projectItem.create({ data: normalizeItem(item, id, index) }); await tx.activityLog.create({ data: { actorUserId: user.id, actorNameSnapshot: user.name, action: existing ? "purchase_order_saved" : "purchase_order_created", entityType: "project", entityId: id, projectId: id, referenceNumber: input.referenceNumber, metadata: { itemCount: input.items.length, originalOfferReference: input.originalOfferReference } } }); return tx.project.findUnique({ where: { id: project.id }, include: { items: { orderBy: { sortOrder: "asc" } }, owner: { select: { id: true, name: true, email: true, signatureStorageKey: true } }, shares: { select: { sharedWithUserId: true, permission: true } }, parentProject: { select: { id: true, referenceNumber: true } } } }); }); }
export async function createPurchaseOrderFromOffer({ user, offerProjectId }: { user: SessionUser; offerProjectId: string }) { if (user.role !== "ADMIN") throw new Error("Admin access required"); const offer = await prisma.project.findUnique({ where: { id: offerProjectId }, include: { items: { orderBy: { sortOrder: "asc" } }, shares: { select: { sharedWithUserId: true, permission: true } } } }); if (!offer || offer.deletedAt || offer.projectType !== "OFFER" || !canAccessProject(user, offer)) throw new Error("Offer not found"); return savePurchaseOrder({ user, input: { referenceNumber: `PO-${offer.referenceNumber}`, status: "PENDING", clientSnapshot: offer.clientSnapshot as never, originalOfferProjectId: offer.id, originalOfferReference: offer.referenceNumber, terms: "", items: offer.items.map((item: any) => ({ sourceType: item.sourceType, catalogItemId: item.catalogItemId, itemCode: item.itemCode, productType: item.productType, make: item.make, model: item.model, approvals: item.approvals, descriptionPlain: item.descriptionPlain, descriptionHtml: item.descriptionHtml, qty: item.qty?.toString(), unit: item.unit, poPriceUsd: item.poPriceUsd?.toString(), poPriceBdt: item.poPriceBdt?.toString() })) } }); }
